<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>6 Comparing means | Quantitative Biology BIOL 275 at MSUM</title>
<meta name="author" content="Chris Merkord">
<meta name="description" content="6.1 Objectives In this lab, you will learn to: Estimate the mean and confidence interval of a numerical variable for two or more groups Plot the distribution of a numerical variable for two or...">
<meta name="generator" content="bookdown 0.24.4 with bs4_book()">
<meta property="og:title" content="6 Comparing means | Quantitative Biology BIOL 275 at MSUM">
<meta property="og:type" content="book">
<meta property="og:description" content="6.1 Objectives In this lab, you will learn to: Estimate the mean and confidence interval of a numerical variable for two or more groups Plot the distribution of a numerical variable for two or...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="6 Comparing means | Quantitative Biology BIOL 275 at MSUM">
<meta name="twitter:description" content="6.1 Objectives In this lab, you will learn to: Estimate the mean and confidence interval of a numerical variable for two or more groups Plot the distribution of a numerical variable for two or...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1.9000/transition.js"></script><script src="libs/bs3compat-0.3.1.9000/tabs.js"></script><script src="libs/bs3compat-0.3.1.9000/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script><script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script><link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="libs/datatables-binding-0.20/datatables.js"></script><link href="libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script><link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script><!-- <link rel="stylesheet" href="https://use.typekit.net/nvk0gxc.css"> --><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="styles.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Quantitative Biology BIOL 275 at MSUM</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Welcome</a></li>
<li class="book-part">Lab Assignments</li>
<li><a class="" href="hello-world.html"><span class="header-section-number">1</span> Hello World!</a></li>
<li><a class="" href="introduction-to-rstudio.html"><span class="header-section-number">2</span> Introduction to RStudio</a></li>
<li><a class="" href="introduction-to-ggplot2.html"><span class="header-section-number">3</span> Introduction to ggplot2</a></li>
<li><a class="" href="data-subsetting.html"><span class="header-section-number">4</span> Data subsetting</a></li>
<li><a class="" href="data-summarizing.html"><span class="header-section-number">5</span> Data summarizing</a></li>
<li><a class="active" href="comparing-means.html"><span class="header-section-number">6</span> Comparing means</a></li>
<li><a class="" href="linear-regression.html"><span class="header-section-number">7</span> Linear regression</a></li>
<li class="book-part">EDA Project</li>
<li><a class="" href="eda-project.html"><span class="header-section-number">8</span> EDA Project</a></li>
<li><a class="" href="sac-application.html"><span class="header-section-number">9</span> SAC Application</a></li>
<li><a class="" href="sac-poster.html"><span class="header-section-number">10</span> SAC Poster</a></li>
<li><a class="" href="data-sets-1.html"><span class="header-section-number">11</span> Data sets</a></li>
<li><a class="" href="public-health-data-sets-1.html"><span class="header-section-number">12</span> Public health data sets</a></li>
<li><a class="" href="ebird-data-sets.html"><span class="header-section-number">13</span> eBird data sets</a></li>
<li class="book-part">Appendices</li>
<li class="book-part">Getting Started</li>
<li><a class="" href="install-r-and-rstudio.html"><span class="header-section-number">16</span> Install R and RStudio</a></li>
<li><a class="" href="install-git.html"><span class="header-section-number">17</span> Install Git</a></li>
<li class="book-part">Using RStudio</li>
<li><a class="" href="project-options.html"><span class="header-section-number">19</span> Project Options</a></li>
<li><a class="" href="code-sections.html"><span class="header-section-number">20</span> Code Sections</a></li>
<li><a class="" href="r-markdown-documents.html"><span class="header-section-number">21</span> R Markdown documents</a></li>
<li><a class="" href="session-info.html"><span class="header-section-number">22</span> Session info</a></li>
<li class="book-part">Git and GitHub</li>
<li><a class="" href="github-notifications.html"><span class="header-section-number">24</span> GitHub Notifications</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/BIOL275-MSUM/BIOL275-MSUM.github.io">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="comparing-means" class="section level1">
<h1>
<span class="header-section-number">6</span> Comparing means<a class="anchor" aria-label="anchor" href="#comparing-means"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-5" class="section level2">
<h2>
<span class="header-section-number">6.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-5"><i class="fas fa-link"></i></a>
</h2>
<p>In this lab, you will learn to:</p>
<ul>
<li>Estimate the mean and confidence interval of a numerical variable for two or more groups</li>
<li>Plot the distribution of a numerical variable for two or more groups</li>
<li>Compare the means of two groups using a two-sample t-test</li>
<li>Compare the means of three or more groups using an ANOVA</li>
</ul>
</div>
<div id="introduction-3" class="section level2">
<h2>
<span class="header-section-number">6.2</span> Introduction<a class="anchor" aria-label="anchor" href="#introduction-3"><i class="fas fa-link"></i></a>
</h2>
<p>A two-sample t-test compares the means of a numerical variable from two separate groups. An ANOVA compares the means of a numerical variable from more than two groups.</p>
<p>In each of these tests, group membership can be thought of as a categorical variable.</p>
<p>The basic ANOVA can be extended to more complicated scenarios. For example, a two-way ANOVA estimates how the means of a numerical variable vary in response to two categorical variables. This lab only deals with one-way ANOVAs.</p>
</div>
<div id="data" class="section level2">
<h2>
<span class="header-section-number">6.3</span> Data<a class="anchor" aria-label="anchor" href="#data"><i class="fas fa-link"></i></a>
</h2>
<p>For this lab, we will use the <code>penguins</code> dataset from the <a href="https://allisonhorst.github.io/palmerpenguins/index.html">palmerpenguins</a> package (Horst et al. 2020).</p>
<div id="installation" class="section level3">
<h3>
<span class="header-section-number">6.3.1</span> Installation<a class="anchor" aria-label="anchor" href="#installation"><i class="fas fa-link"></i></a>
</h3>
<p>You can install the release version of palmerpenguins from CRAN using the Packages tab in RStudio or with:</p>
<div class="sourceCode" id="cb175"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"palmerpenguins"</span><span class="op">)</span></code></pre></div>
<p>This only needs to be done once on your computer, so it’s best not to put this in your R script. If you do put it in, prefix it with a comment so it does not run each time your run through your script:</p>
<div class="sourceCode" id="cb176"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># install.packages("palmerpenguins")</span></code></pre></div>
<p>Then load the package. While you’re at it, go ahead and load the tidyverse too, because we will also use that in this lab:</p>
<div class="sourceCode" id="cb177"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://allisonhorst.github.io/palmerpenguins/">palmerpenguins</a></span><span class="op">)</span></code></pre></div>
<p>While not required to access the data, it is nice to see the dataset in your Environment. You can load the <code>penguins</code> dataset with:</p>
<div class="sourceCode" id="cb178"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"penguins"</span><span class="op">)</span></code></pre></div>
<p>You should now see two datasets in your Environment, <code>penguins</code> and <code>penguins_raw</code>. For this lab we will use <code>penguins</code> only. The details for each dataset will not be shown in the Environment tab until you use them (see the next section), a result of something called lazy-loading, which prevents the dataset from taking up memory until you need to use it.</p>
</div>
<div id="about-the-data" class="section level3">
<h3>
<span class="header-section-number">6.3.2</span> About the data<a class="anchor" aria-label="anchor" href="#about-the-data"><i class="fas fa-link"></i></a>
</h3>
<p>The dataset <code>penguins</code> contains data for 344 penguins, of 3 different species, collected from 3 islands in the Palmer Archipelago, Antarctica.</p>
<div class="sourceCode" id="cb179"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">penguins</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 6 × 8
#&gt;   species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g sex  
#&gt;   &lt;fct&gt;   &lt;fct&gt;           &lt;dbl&gt;         &lt;dbl&gt;            &lt;int&gt;       &lt;int&gt; &lt;fct&gt;
#&gt; 1 Adelie  Torge…           39.1          18.7              181        3750 male 
#&gt; 2 Adelie  Torge…           39.5          17.4              186        3800 fema…
#&gt; 3 Adelie  Torge…           40.3          18                195        3250 fema…
#&gt; 4 Adelie  Torge…           NA            NA                 NA          NA &lt;NA&gt; 
#&gt; 5 Adelie  Torge…           36.7          19.3              193        3450 fema…
#&gt; 6 Adelie  Torge…           39.3          20.6              190        3650 male 
#&gt; # … with 1 more variable: year &lt;int&gt;</code></pre>
<p>The three islands include Torgersen, Biscoe, and Dream while the three species of penguins include Chinstrap, Gentoo, and Adélie.</p>
<div class="inline-figure"><img src="https://allisonhorst.github.io/palmerpenguins/reference/figures/lter_penguins.png" width="50%"></div>
<p>For each penguin (i.e. row, i.e. observation, i.e. case), has measurements for bill length (mm), bill depth (mm), flipper length (mm), body mass (g), sex (male or female), and year (2007, 2008, 2009).</p>
<p>Bill length, or more specifically culmen lenght, is the distance from the tip of the bill to the base of the upper mandible. Bill depth is the distance from the top of the bill to the bottom at the base of the bill.</p>
<div class="inline-figure"><img src="https://allisonhorst.github.io/palmerpenguins/reference/figures/culmen_depth.png" width="50%"></div>
<p>Looking at the structure of the dataset, you can see that species, island, and sex are factors, bill_length_mm and bill_depth_mm are doubles, and the other variables are integers.</p>
<div class="sourceCode" id="cb181"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">penguins</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; tibble [344 × 8] (S3: tbl_df/tbl/data.frame)
#&gt;  $ species          : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
#&gt;  $ island           : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
#&gt;  $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
#&gt;  $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
#&gt;  $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...
#&gt;  $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
#&gt;  $ sex              : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
#&gt;  $ year             : int [1:344] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...</code></pre>
</div>
</div>
<div id="compare-two-groups" class="section level2">
<h2>
<span class="header-section-number">6.4</span> Compare two groups<a class="anchor" aria-label="anchor" href="#compare-two-groups"><i class="fas fa-link"></i></a>
</h2>
<div id="sexual-dimorphism" class="section level3">
<h3>
<span class="header-section-number">6.4.1</span> Sexual dimorphism<a class="anchor" aria-label="anchor" href="#sexual-dimorphism"><i class="fas fa-link"></i></a>
</h3>
<p>Many bird species show a pattern of sexual dimorphism, with males averaging larger than females. In some groups, however, many species show reverse sexual dimorphism, with females averaging larger than males. This is most common in birds of prey including Falconiformes (falcons), Strigiformes (owls), and Accipitriformes (hawks, eagles, kites, etc.).</p>
<p>The term “bird of prey” is a somewhat ambiguous term for species that primarily hunt and feed on vertebrates. Penguins fit that description, but have not historically been considered “birds of prey”.</p>
<p>Let’s explore the penguins dataset to see if there is evidence of either type of sexual dimorphism in these species:</p>
<div class="sourceCode" id="cb183"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">penguins</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span>
    <span class="va">species</span>,
    <span class="va">sex</span>,
    <span class="va">bill_length_mm</span>, 
    <span class="va">bill_depth_mm</span>, 
    <span class="va">flipper_length_mm</span>, 
    <span class="va">body_mass_g</span>
  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>
    col <span class="op">=</span> <span class="fu">where</span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>,
    names_to <span class="op">=</span> <span class="st">"variable"</span>, 
    values_to <span class="op">=</span> <span class="st">"value"</span>
  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/complete.cases.html">complete.cases</a></span><span class="op">(</span><span class="va">.</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sex</span>, y <span class="op">=</span> <span class="va">value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color <span class="op">=</span> <span class="va">sex</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_grid.html">facet_grid</a></span><span class="op">(</span><span class="va">variable</span> <span class="op">~</span> <span class="va">species</span>, scales <span class="op">=</span> <span class="st">"free_y"</span>, switch <span class="op">=</span> <span class="st">"y"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guides.html">guides</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>strip.placement <span class="op">=</span> <span class="st">"outside"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="lab-6_files/figure-html/strip-chart-sex-1.png" width="70%" style="display: block; margin: auto;"></div>
<p>There certainly appears to be some difference between males and females, at least for some morphological characteristics and species.</p>
</div>
<div id="adélie-bill-depth" class="section level3">
<h3>
<span class="header-section-number">6.4.2</span> Adélie bill depth<a class="anchor" aria-label="anchor" href="#ad%C3%A9lie-bill-depth"><i class="fas fa-link"></i></a>
</h3>
<p>Let’s dig in an look more closely at one variable and one species: Adélie Penguins and bill depth.</p>
<div class="sourceCode" id="cb184"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">adelie_bill_depth</span> <span class="op">&lt;-</span>
  <span class="va">penguins</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">species</span> <span class="op">==</span> <span class="st">"Adelie"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">sex</span>, <span class="va">bill_depth_mm</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/complete.cases.html">complete.cases</a></span><span class="op">(</span><span class="va">.</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 146 × 2
#&gt;   sex    bill_depth_mm
#&gt;   &lt;fct&gt;          &lt;dbl&gt;
#&gt; 1 male            18.7
#&gt; 2 female          17.4
#&gt; 3 female          18  
#&gt; 4 female          19.3
#&gt; 5 male            20.6
#&gt; 6 female          17.8
#&gt; # … with 140 more rows</code></pre>
<p>As you can see, there are 146 Adélie penguins in the dataset.</p>
</div>
<div id="distribution-of-bill-depths-by-sex" class="section level3">
<h3>
<span class="header-section-number">6.4.3</span> Distribution of bill depths by sex<a class="anchor" aria-label="anchor" href="#distribution-of-bill-depths-by-sex"><i class="fas fa-link"></i></a>
</h3>
<p>Next, let’s see how the variable bill depth is distributed in each sex:</p>
<div class="sourceCode" id="cb186"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">adelie_bill_depth</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">bill_depth_mm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="va">sex</span><span class="op">)</span>, 
    bins <span class="op">=</span> <span class="fl">15</span>, 
    alpha <span class="op">=</span> <span class="fl">0.5</span>, 
    position <span class="op">=</span> <span class="st">"identity"</span>
  <span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkorange"</span>,<span class="st">"cyan4"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="lab-6_files/figure-html/adelie-bill-depth-histogram-1.png" width="70%" style="display: block; margin: auto;"></div>
<p>The distributions are not perfectly normal, but the general hump shape is close enough that we should feel comfortable assuming they are normally distributed for the purpose of estimating population parameters and conducting hypothesis tests.</p>
</div>
<div id="mean-bill-depth-by-sex" class="section level3">
<h3>
<span class="header-section-number">6.4.4</span> Mean bill depth by sex<a class="anchor" aria-label="anchor" href="#mean-bill-depth-by-sex"><i class="fas fa-link"></i></a>
</h3>
<p>Next we will estimate the mean bill depth for each sex and put a 95% confidence interval around those estimates:</p>
<div class="sourceCode" id="cb187"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">adelie_bill_depth_summary</span> <span class="op">&lt;-</span>
  <span class="va">adelie_bill_depth</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>
    n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>,
    mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">bill_depth_mm</span><span class="op">)</span>,
    sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">bill_depth_mm</span><span class="op">)</span>,
    sem <span class="op">=</span> <span class="va">sd</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>,
    upper <span class="op">=</span> <span class="va">mean</span> <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> <span class="va">sem</span>,
    lower <span class="op">=</span> <span class="va">mean</span> <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> <span class="va">sem</span>
  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 2 × 7
#&gt;   sex        n  mean    sd   sem upper lower
#&gt;   &lt;fct&gt;  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 female    73  17.6 0.943 0.110  17.8  17.4
#&gt; 2 male      73  19.1 1.02  0.119  19.3  18.8</code></pre>
<p>Here we can see that the confidence intervals for our estimates of the mean bill depth for each each sex do not overlap. To make it more clear, let’s plot it:</p>
<div class="sourceCode" id="cb189"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">adelie_bill_depth</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sex</span>, y <span class="op">=</span> <span class="va">bill_depth_mm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color <span class="op">=</span> <span class="va">sex</span><span class="op">)</span>, 
              shape <span class="op">=</span> <span class="fl">16</span>, alpha <span class="op">=</span> <span class="fl">0.3</span>, width <span class="op">=</span> <span class="fl">0.4</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">mean</span>, ymax <span class="op">=</span> <span class="va">upper</span>, ymin <span class="op">=</span> <span class="va">lower</span><span class="op">)</span>, 
                data <span class="op">=</span> <span class="va">adelie_bill_depth_summary</span>, width <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">mean</span><span class="op">)</span>, 
             data <span class="op">=</span> <span class="va">adelie_bill_depth_summary</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_color_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkorange"</span>,<span class="st">"cyan4"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guides.html">guides</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="lab-6_files/figure-html/adelie-bill-depth-means-1.png" width="70%" style="display: block; margin: auto;"></div>
<p>The non-overlapping confidence intervals can be seen clearly in the above figure.</p>
</div>
<div id="t-test" class="section level3">
<h3>
<span class="header-section-number">6.4.5</span> <span class="math inline">\(t\)</span>-test<a class="anchor" aria-label="anchor" href="#t-test"><i class="fas fa-link"></i></a>
</h3>
<p>To compare the means using a hypothesis test, we can use a two-sample t-test.</p>
<p>The null hypothesis would be that the mean bill depths of females and males are equal. The alternative hypothesis would be that the mean bill depths of females are males are not equal.</p>
<p>Now we can use the function <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> to conduct the t-test. The first argument will be a formula specifying how the variables are related. The numerical (response) variable should go first, followed by a tilde <code>~</code>, then the categorical (explanatory) variable. The other required argument is the name of the dataset.</p>
<div class="sourceCode" id="cb190"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ttest_results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">bill_depth_mm</span> <span class="op">~</span> <span class="va">sex</span>, data <span class="op">=</span> <span class="va">adelie_bill_depth</span><span class="op">)</span>
<span class="va">ttest_results</span></code></pre></div>
<pre><code>#&gt; 
#&gt;  Welch Two Sample t-test
#&gt; 
#&gt; data:  bill_depth_mm by sex
#&gt; t = -8.928, df = 143.15, p-value = 1.914e-15
#&gt; alternative hypothesis: true difference in means between group female and group male is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -1.77187 -1.12950
#&gt; sample estimates:
#&gt; mean in group female   mean in group male 
#&gt;             17.62192             19.07260</code></pre>
<p>The output shows several things:</p>
<ul>
<li>the two variables involved</li>
<li>the test statistic <span class="math inline">\(t\)</span>
</li>
<li>the degrees of freedom</li>
<li>the <span class="math inline">\(P\)</span>-value</li>
<li>the alternative hypothesis</li>
<li>the 95% confidence interval of the <em>difference</em> in the two means</li>
<li>the estimated mean for each group</li>
</ul>
<p>In this case, the <span class="math inline">\(P\)</span>-value is <code>1.914e-15</code>, which is scientific notation for 0.000000000000001914. If we choose an alpha level of <span class="math inline">\(\alpha=0.05\)</span>, then <span class="math inline">\(P &lt; \alpha\)</span>, so we can reject the null hypothesis and accept the alternative hypothesis by default.</p>
<p>You can find the difference in the two means like this:</p>
<div class="sourceCode" id="cb192"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diff.html">diff</a></span><span class="op">(</span><span class="va">ttest_results</span><span class="op">$</span><span class="va">estimate</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; [1] 1.450685</code></pre>
<p>To conclude: Female Adélie Penguins are 1.45 mm shorter than males (95% CI 1.13–1.77). The difference is statistically significant (<span class="math inline">\(t = -8.928\)</span>, <span class="math inline">\(df = 143.15\)</span>, <span class="math inline">\(p = 1.914e-15\)</span>).</p>
</div>
</div>
<div id="compare-three-groups" class="section level2">
<h2>
<span class="header-section-number">6.5</span> Compare three groups<a class="anchor" aria-label="anchor" href="#compare-three-groups"><i class="fas fa-link"></i></a>
</h2>
<div id="distribution-of-bill-depths-by-species" class="section level3">
<h3>
<span class="header-section-number">6.5.1</span> Distribution of bill depths by species<a class="anchor" aria-label="anchor" href="#distribution-of-bill-depths-by-species"><i class="fas fa-link"></i></a>
</h3>
<p>For the next exercise, we will compare the mean bill depth among three groups: the three species of penguins. First, let’s look at the distribution of bill depths for each species:</p>
<div class="sourceCode" id="cb194"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">penguins</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">bill_depth_mm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="va">species</span><span class="op">)</span>, 
    bins <span class="op">=</span> <span class="fl">15</span>, 
    alpha <span class="op">=</span> <span class="fl">0.5</span>, 
    position <span class="op">=</span> <span class="st">"identity"</span>,
    na.rm <span class="op">=</span> <span class="cn">TRUE</span>
  <span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkorange"</span>, <span class="st">"darkorchid"</span>, <span class="st">"cyan4"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="lab-6_files/figure-html/bill-depth-species-histogram-1.png" width="70%" style="display: block; margin: auto;"></div>
<p>It certainly appears that Gentoo Penguins have shorter bills than the other two species.</p>
</div>
<div id="mean-bill-depth-by-species" class="section level3">
<h3>
<span class="header-section-number">6.5.2</span> Mean bill depth by species<a class="anchor" aria-label="anchor" href="#mean-bill-depth-by-species"><i class="fas fa-link"></i></a>
</h3>
<p>Next, we will estimate the mean bill depth for each species and put a confidence interval around each estimate:</p>
<div class="sourceCode" id="cb195"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">bill_depth_means</span> <span class="op">&lt;-</span>
  <span class="va">penguins</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">bill_depth_mm</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>      <span class="co"># remove missing values</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">species</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>
    mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">bill_depth_mm</span><span class="op">)</span>,
    sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">bill_depth_mm</span><span class="op">)</span>,
    n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>,
    sem <span class="op">=</span> <span class="va">sd</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>,
    upper <span class="op">=</span> <span class="va">mean</span> <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> <span class="va">sem</span>,
    lower <span class="op">=</span> <span class="va">mean</span> <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> <span class="va">sem</span>
  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt; # A tibble: 3 × 7
#&gt;   species    mean    sd     n    sem upper lower
#&gt;   &lt;fct&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 Adelie     18.3 1.22    151 0.0990  18.5  18.2
#&gt; 2 Chinstrap  18.4 1.14     68 0.138   18.7  18.2
#&gt; 3 Gentoo     15.0 0.981   123 0.0885  15.2  14.8</code></pre>
<p>And here are those means and confidence intervals plotted over the raw data:</p>
<div class="sourceCode" id="cb197"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">species</span>, y <span class="op">=</span> <span class="va">bill_depth_mm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>color <span class="op">=</span> <span class="va">species</span><span class="op">)</span>,
              width <span class="op">=</span> <span class="fl">0.1</span>,
              alpha <span class="op">=</span> <span class="fl">0.7</span>,
              show.legend <span class="op">=</span> <span class="cn">FALSE</span>,
              na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">mean</span>, ymin <span class="op">=</span> <span class="va">lower</span>, ymax <span class="op">=</span> <span class="va">upper</span><span class="op">)</span>, 
                data <span class="op">=</span> <span class="va">bill_depth_means</span>,
                width <span class="op">=</span> <span class="fl">.1</span>, position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_nudge.html">position_nudge</a></span><span class="op">(</span><span class="fl">.3</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">mean</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">bill_depth_means</span>,
             position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_nudge.html">position_nudge</a></span><span class="op">(</span><span class="fl">.3</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_color_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkorange"</span>,<span class="st">"darkorchid"</span>,<span class="st">"cyan4"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="lab-6_files/figure-html/bill-depth-jitter-1.png" width="70%" style="display: block; margin: auto;"></div>
<p>The graph, which depicts the mean 95% confidence interval for the bill depth of each species, indicates there is likely a statistically significant difference between the means.</p>
</div>
<div id="anova" class="section level3">
<h3>
<span class="header-section-number">6.5.3</span> ANOVA<a class="anchor" aria-label="anchor" href="#anova"><i class="fas fa-link"></i></a>
</h3>
<p>To test this hypothesis, we can use a one-way ANOVA, which tests for differences among the means of multiple groups.</p>
<p>The hypotheses for an ANOVA can be state like this:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: the mean bill depth is equal among all species</li>
<li>
<span class="math inline">\(H_A\)</span>: At least one bill depth is different from the others</li>
</ul>
<p>The <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> function fits an analysis of variance model to the data. The first argument is the formula specifying how the variables are related, just like the <span class="math inline">\(t\)</span>-test, with the numerical response variable, a tilde, and the categorical explanatory variable. The other argument is the data frame.</p>
<div class="sourceCode" id="cb198"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">aov_bill_depth_species</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">bill_depth_mm</span> <span class="op">~</span> <span class="va">species</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span>
<span class="va">aov_bill_depth_species</span></code></pre></div>
<pre><code>#&gt; Call:
#&gt;    aov(formula = bill_depth_mm ~ species, data = penguins)
#&gt; 
#&gt; Terms:
#&gt;                  species Residuals
#&gt; Sum of Squares  903.9672  425.8673
#&gt; Deg. of Freedom        2       339
#&gt; 
#&gt; Residual standard error: 1.120824
#&gt; Estimated effects may be unbalanced
#&gt; 2 observations deleted due to missingness</code></pre>
<p>Printing the results of the ANOVA, as seen above, gives you some information about the test, but using the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function gives you more details:</p>
<div class="sourceCode" id="cb200"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">aov_bill_depth_species</span><span class="op">)</span></code></pre></div>
<pre><code>#&gt;              Df Sum Sq Mean Sq F value Pr(&gt;F)    
#&gt; species       2  904.0   452.0   359.8 &lt;2e-16 ***
#&gt; Residuals   339  425.9     1.3                   
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 2 observations deleted due to missingness</code></pre>
<p>ANOVA works by comparing the variance within groups to the variance between groups. The test statistic is the <span class="math inline">\(F\)</span>-ratio, where <span class="math inline">\(F=MS_{groups}/MS_{error}\)</span>. Under the null hypothesis, F would be close to 1, while under the alternative hypothesis F would be greater than 1. The <span class="math inline">\(P\)</span>-value represents the probability of obtaining an F-ratio as great as or greater than the one you obtained. If the <span class="math inline">\(P\)</span>-value is less than your alpha level, you can reject the null hypothesis.</p>
<p>In this case, the <span class="math inline">\(P\)</span>-value of <code>2e-16</code> is below a any alpha level we might choose, so we can reject the null hypothesis and conclude that the mean bill depth for at least one species is different from the means for the other species.</p>
</div>
</div>
<div id="assignment-2" class="section level2">
<h2>
<span class="header-section-number">6.6</span> Assignment<a class="anchor" aria-label="anchor" href="#assignment-2"><i class="fas fa-link"></i></a>
</h2>
<div id="instructions-1" class="section level3">
<h3>
<span class="header-section-number">6.6.1</span> Instructions<a class="anchor" aria-label="anchor" href="#instructions-1"><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: decimal">
<li>
<p>Claim your repository for this lab using the GitHub Classrooms link posted on D2L.</p>
<ul>
<li>Your new repository will be created using this repository as a template: <a href="https://github.com/BIOL275-MSUM/lab-6-template" class="uri">https://github.com/BIOL275-MSUM/lab-6-template</a>
</li>
<li>The template repository has the necessary scripts and data files to get you started</li>
<li>You do not need to create any new files</li>
</ul>
</li>
<li><p>Create a new RStudio project by cloning the repository from GitHub</p></li>
<li><p>Read the questions on your README (you can also <a href="https://github.com/BIOL275-MSUM/lab-6-template#readme">read them on the template file on GitHub</a>)</p></li>
<li><p>Fill out the R script to complete your analysis</p></li>
<li><p>When you are satisfied, copy the R code to your README file, knit the document, commit everything, and push it to GitHub.</p></li>
<li><p>Submit the link to your GitHub repo to the D2L assignment box for this lab so it can be graded.</p></li>
</ol>
</div>
</div>
<div id="references" class="section level2">
<h2>
<span class="header-section-number">6.7</span> References<a class="anchor" aria-label="anchor" href="#references"><i class="fas fa-link"></i></a>
</h2>
<p>Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer Archipelago (Antarctica) penguin data. R package version 0.1.0. <a href="https://allisonhorst.github.io/palmerpenguins/" class="uri">https://allisonhorst.github.io/palmerpenguins/</a></p>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="data-summarizing.html"><span class="header-section-number">5</span> Data summarizing</a></div>
<div class="next"><a href="linear-regression.html"><span class="header-section-number">7</span> Linear regression</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#comparing-means"><span class="header-section-number">6</span> Comparing means</a></li>
<li><a class="nav-link" href="#objectives-5"><span class="header-section-number">6.1</span> Objectives</a></li>
<li><a class="nav-link" href="#introduction-3"><span class="header-section-number">6.2</span> Introduction</a></li>
<li>
<a class="nav-link" href="#data"><span class="header-section-number">6.3</span> Data</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#installation"><span class="header-section-number">6.3.1</span> Installation</a></li>
<li><a class="nav-link" href="#about-the-data"><span class="header-section-number">6.3.2</span> About the data</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#compare-two-groups"><span class="header-section-number">6.4</span> Compare two groups</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#sexual-dimorphism"><span class="header-section-number">6.4.1</span> Sexual dimorphism</a></li>
<li><a class="nav-link" href="#ad%C3%A9lie-bill-depth"><span class="header-section-number">6.4.2</span> Adélie bill depth</a></li>
<li><a class="nav-link" href="#distribution-of-bill-depths-by-sex"><span class="header-section-number">6.4.3</span> Distribution of bill depths by sex</a></li>
<li><a class="nav-link" href="#mean-bill-depth-by-sex"><span class="header-section-number">6.4.4</span> Mean bill depth by sex</a></li>
<li><a class="nav-link" href="#t-test"><span class="header-section-number">6.4.5</span> \(t\)-test</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#compare-three-groups"><span class="header-section-number">6.5</span> Compare three groups</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#distribution-of-bill-depths-by-species"><span class="header-section-number">6.5.1</span> Distribution of bill depths by species</a></li>
<li><a class="nav-link" href="#mean-bill-depth-by-species"><span class="header-section-number">6.5.2</span> Mean bill depth by species</a></li>
<li><a class="nav-link" href="#anova"><span class="header-section-number">6.5.3</span> ANOVA</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#assignment-2"><span class="header-section-number">6.6</span> Assignment</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#instructions-1"><span class="header-section-number">6.6.1</span> Instructions</a></li></ul>
</li>
<li><a class="nav-link" href="#references"><span class="header-section-number">6.7</span> References</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/BIOL275-MSUM/BIOL275-MSUM.github.io/blob/master/lab-6.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/BIOL275-MSUM/BIOL275-MSUM.github.io/edit/master/lab-6.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Quantitative Biology BIOL 275 at MSUM</strong>" was written by Chris Merkord. It was last built on 2022-01-06.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
