# Public health data sets

Various government and non-profit organizations collect, organize, and make available data sets related to public health.

## National Center for Health Statistics

<https://www.cdc.gov/nchs/data_access/ftp_data.htm>

The National Center for Health Statistics (NCHS) offers downloadable public-use data files through the Centers for Disease Control and Prevention's (CDC) FTP file server. Users of this service have access to [data sets](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets), [documentation](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation), and [questionnaires](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Survey_Questionnaires) from NCHS surveys and data collection systems. Downloading instructions are available in "readme" files.

Users of NCHS public-use data files must comply with [data use restrictions](https://www.cdc.gov/nchs/data_access/restrictions.htm) to ensure that the information will be used solely for statistical analysis or reporting purposes.

## County Health Rankings & Roadmaps

[County Health Rankings & Roadmaps](http://www.countyhealthrankings.org/) provides annual county-level public health data.

You can download data by state and year (for example, see [Minnesota](http://www.countyhealthrankings.org/app/minnesota/2017/downloads).

## KIDS COUNT

[KIDS COUNT](http://datacenter.kidscount.org/) provides county- and state-level data on children and families and a project of the Annie E. Casey Foundation.

Data is available by year and county/state.

You would need to choose and download the variables necessary to answer your question. Topics include:

-   Demographics
-   Economic Well-Being
-   Education
-   Family and Community
-   Health
-   Safety and Risky Behaviors

## Links to other data sets

-   [**Minnesota Health Data Sources**](http://www.countyhealthrankings.org/using-the-rankings-data/finding-more-data/minnesota), a list compiled by County Health Rankings & Roadmaps.
