---
title: "GitHub Practice Assignment"
date: "Updated 2017-02-27"
output: html_document
---

## Learning Objectives

In this assignment you will learn to:
- [Claim a GitHub repository](claim_repo.html) via GitHub Classroom.
- Use Git for version control.
- Create a README file using Markdown syntax.
- Use code headings, comments, and white space to make a readable, understandable R script.
- Use the [R Markdown to GitHub pipeline](rmd_pipeline.html) to create pretty output on GitHub


## Sections

- [Create your GitHub account]
- [Claim your GitHub repo]
- [Project setup]
- [Assignment]
- [What to "turn in"]

## Create your GitHub account

By now you should already have:

1. Created your [GitHub](https://github.com/) account following the directions in the **Create GitHub Account** assignment
2. Posted your user name on the shared Google Sheet (see [D2L](https://mnstate.learn.minnstate.edu/d2l/home/4541637) for the link)

If not, please do so now.

## Claim your GitHub repo

Your instructor has created your first GitHub repository for you. Follow these instructions:

1. Go to [D2L](https://mnstate.learn.minnstate.edu/d2l/home/4541637).
2. Navigate to **Materials** > **Content** > **Lab** > **GitHub** and click the link for **Claim GitHub Practice repistory**. This will take you to the GitHub Classroom website.
3. Follow the rest of the instructions for [Claiming a GitHub Classroom repository](claim_repo.html).

This process will automatically create a repository for you on GitHub, pre-loaded with the necessary files.

## Project setup

Now you need to get your repository onto your local computer.

Follow these instructions:

1. Open RStudio
2. **Create a new RStudio project**
3. Select the **Version Control** option
4. For Repository URL, paste in the URL for your repository, e.g. https://github.com/chrismerkord/github-practice
5. The project name field should fill itself in automatically, but if it doesn't, type the name of your repository as it appears in the URL above (and on GitHub), e.g. `github-practice`
3. Choose a folder location where you can find it again. Pay attention to where you save it. You should be able to navigate to this folder in your file browser if necessary. If you are using a USB flash drive, create the new project right on your flash drive.

When you click finish, RStudio will restart with your new project open.

In addition to the usual tabs available in RStudio, there will be a new Git tab in the upper right pane.

## Assignment

Here are the basic steps to your assignment. Your instructor will provide more details.

1. Create a README.md file.
    1. Create a new file called README.md (exactly like that)
    2. In the new file, enter a heading like `## GitHub Practice Assignment` or something similar, followed by a blank line
    3. Add a sentence describing the purpose of this repo, followed by a blank line.
    4. Add a list of important files in the repo. You can create a list by preceding each line with an asterisk `*`. For extra credit, create a link to your analysis Markdown document (which isn't created yet, but will be in a subsequent step).
    4. Save the file, commit your changes, and push the commit to GitHub
2. Starting with the most blank R script:
    - Copy code from the [Finches Analysis](finches_analysis.html) and paste it into the appropriate areas in the script. 
    - Don't delete and code headings or comments in the script. 
    - This is your chance to see a nicely formatted, readable, well-commented, understandble script!
    - Run the code in the script to make sure it all works.
4. Create a Markdown document to show off your analysis. The goal is to end up with a document that looks like the [Finches Analysis](finches_analysis.html) file... a pretty explanation of your analysis, including code, console output, and plots.
    1. Start by creating an R Markdown file. See [The RMarkdown to GitHub Pipeline](rmd_pipeline.html) for instructions.
    2. Delete the headings, text, and the last two R code chunks.
    2. For each code section in the script, you should have:
        - a plain text sentence describing what you are doing
        - the R code
        - the output of the code (if any)
    3. To insert R code:
        - Click the Insert button, then R. This will insert an empty R code chunk.
        - Copy code from your R script, and paste it into the empty R code chunk, between the two sets of triple back ticks.
    5. Knit the script to create a markdown (.md) file.
        - Click "Knit"
        - A preview will pop up in its own window.
6. Add all files to GitHub and commit
7. Push all commits to GitHub and double check that the .md file renders correctly.

For more detailed instructions on steps 3-5, see [The RMarkdown to GitHub Pipeline](rmd_pipeline.html).

## What to "turn in"

Your repository should end up with the following four files in it:

1. the R project file `github-practice-username.Rproj`
2. an R script `github-practice.R`
3. an Rmd file `github-practice.Rmd`
3. a Markdown document `github-practice.md`
4. a README file `README.md` for the repository
5. `.gitignore`

You will be graded on the files in your GitHub repo. Specifically, the content of the markdown document and the README file.