---
title: "Homework 1"
date: "Updated 2017-01-17"
output: html_document
---

The purpose of Lab 1 is to introduce you to R, RStudio, Git, and GitHub.

You will work through Chapter 1 in the lab textbook and "turn in" your homework by pushing your files to a GitHub repository for Homework 1.

## Overview

- [Create your GitHub account](#create-your-github-account)
- [System setup](#system-setup)
- [Getting acquainted with R](#getting-acquainted-with-R)
- [Project setup](#project-setup)
- [Your first script](#your-first-script)
- [What to turn in](#what-to-turn-in)

## Create your GitHub account

If you don't have an account on GitHub then create one now: https://github.com/

Be sure to use a username and password you can remember easily, or write them down and have them available in class. You will need to sign in to GitHub fairly often.

After creating your account you will need to verify your email address.

## System setup

You must have R, RStudio, and Git installed on your machine. In addition, there may be some other requirements for setting up Git. 

How you proceed with setup will depend on whether you plan to use computer lab machines or your personal laptop. You can switch back and forth, for example if you get a new laptop halfway through the semester or if you forget your laptop one day.

### Setting up a computer lab machine

#### Install Git

Check to see if git is installed. If not, then install it from https://git-scm.com/downloads.

### Setting up a personal laptop

#### Install R

Install R version 3.4.3. See section 1.2 in GSR for directions or follow these simplified directions:

1. Go to https://cloud.r-project.org/
2. Click the link for your operating system: Linux, Mac, or Windows
3. If you have Windows, click `base` and then click `Download R 3.4.3 for Windows`.
4. If you have a Mac, click `R-3.4.3.pkg`.

#### Install RStudio

Install the most recent version of RStudio: https://www.rstudio.com/products/rstudio/download/

As of today the most recent version is 1.1.414. Version 1.1.383 was the version at the beginning of the semester. Either of these, or any subsequent version 1.1.xxx releases should be fine.

#### Install and configure Git

See instructions above for installing Git.

Once you have it installed, you will need to configure some settings. 

Run the program Git Bash (on Windows) or Git (?) (on Mac), which will open a terminal window. In this window, there will be a command prompt. Run the following two commands.

    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"

In the code above replace "you@example.com" with your email address and replace "Your Name" with your name, for example "Chris Merkord".

After typing each command press Enter before typing the next command. Commands must be typed exactly as shown. Spaces and capitalization matter. Terminal windows are tricky so its best to type the commands rather than trying to copy and paste them from here.

## Getting acquainted with R

Work through sections 1.3 to 1.5 in GSR.

## Project setup

You will create a new RStudio project and Git repository for this assignment.

Here are the instructions for creating your project:

1. Claim your Homework 1 repository on GitHub. Detailed instructions on claiming a repository can be found [here](claim_repo.html).
2. Create a new RStudio project (select version control option). Pay very careful attention to the folder on your computer where you create the project. You should be able to navigate to this folder in your file browser. If you are using a USB flash drive, create the new project right on your flash drive.

An intro to git: staging, committing, and pushing:

- Stage the R project file and .gitignore file. commit and push.
- Edit the README. Save your changes, stage, commit, and push.

## Your first script

Work through sections 1.6 to 1.11. If you need some help with the mini-practical, check out Appendix 1a.

## What to turn in

Your repository should end up with the following four files in it:

1. the R project file `hw1-username.Rproj`
2. an R script `hw1.R`
4. a README file `README.md` for the repository
5. `.gitignore`