# (PART) Lab Assignments {.unnumbered}

# Lab 1: Introduction to R and RStudio

The course tools for the lab include the software programs R and RStudio.

## Learning Outcomes

Students will be able to:

1.  Know the difference between R and RStudio, how to run the applications, and which one to use choose
2.  Identify the various panes and tabs in RStudio
3.  Use the Console tab to run commands
    a.  Locate the command prompt in the Console tab
    b.  Run a command
    c.  Locate the output after running a command
    d.  Distinguish between a clean prompt and a waiting prompt, and clear a waiting prompt
    e.  Scroll through previous commands with the up and down arrows
4.  Use the History tab to view previous commands and copy them to the console
5.  Run commands using arithmetic operators
    a.  Know the basic arithmetic operators `+`, `-`, `/`, `*`, `^`
    b.  Use them to perform mathematical computations
    c.  Understand the order of operations and manipulate it using parentheses
6.  Use simple functions
    a.  Use the basic arithmetic functions for square root `sqrt()` and absolute value `abs()`
    b.  Identify objects as functions or values
7.  Work with objects
    1.  Use the assignment operator `<-` to assign values to objects
    2.  Print objects in the console by running their name
    3.  Print objects in the console using the `print()` function
    4.  Locate the Environment tab and identify objects in the environment
    5.  List objects in the environment using the `ls()` function
    6.  Remove some or all objects from the environment using the Environment tab
    7.  Remove some or all objects from the environment using the `rm()` function
8.  Distinguish between values, objects, and functions

## Assignment

1.  Follow along as your instructor introduces you to R and RStudio
2.  Keep written notes of how to complete each step
3.  Conduct a self-assessment of the learning outcomes listed above. Report the outcome to your instructor.

## Checklist

Check your skills and comprehension; you should be able to do the following:

-   Use the Windows operating system
    -   Run programs
        -   [ ] Use Windows Start Menu
        -   [ ] Run a given version of R using 32-bit or 64-bit
        -   [ ] Run RStudio
    -   Work with folders and files
        -   [ ] Run File Explorer on Windows
        -   [ ] Open Documents folder through Quick Access
        -   [ ] Open Documents folder through the C drive
        -   [ ] Move and rename files and folders
-   Use R
    -   Work in the R Console
        -   [ ] Find the command prompt (\>)
        -   [ ] Discern the status of the command prompt (ready \>, waiting +, unrun code)
        -   [ ] Escape a waiting command prompt (Esc)
        -   [ ] Clear unrun code on a command prompt (Esc/Backspace)
        -   [ ] Run a command (line of code)
        -   [ ] Scroll through previous commands (up arrow)
    -   Do math
        -   [ ] Use numbers and operators + - \* / \^ to do math
        -   [ ] Control order of operators using parentheses ( )
        -   [ ] Use math functions sqrt() and abs()
    -   Work with objects in the global environment
        -   [ ] Use assignment operator \<- to create an object
        -   [ ] Identify valid and invalid object names:doesn't start with a number, contains only letters, numbers, . and \_
        -   [ ] Print an object in the console by running its name
        -   [ ] Print an object in the console using print()
        -   [ ] List the objects in the global environment using ls()
        -   [ ] Remove an object from the global environment using rm()
        -   [ ] Remove all objects from the environment using rm(list = ls())
