---
title: "Lab practical study guide"
output: html_document
---

## Format of the practical

You will demonstrate in lab using R and RStudio that you know how to create a project, save data files into it, create an R script, and write R code. I will grade the assignment in lab when you are finished with it, before you leave.

## Practice example

```{r create-example, message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
set.seed(2)
tibble(
  A = rnorm(20, 5, 1),
  B = rnorm(20, 10, 2),
  C = rnorm(20, 20, 4)
) %>% 
  gather(species, height) %>%
  sample_frac(.95) %>% 
  mutate(
    height = ifelse(runif(n()) > .9, NA, height),
    add = rnorm(n(), 1, .1),
    mult = rnorm(n(), 3, .1),
    weight = (height + add) * mult
  ) %>% 
  select(-add, -mult) %>% 
  write.csv("sample-data.csv", row.names = FALSE)
```

You will be given a dataset and a prompt. Here is an example:

1. Create a new project in RStudio
    - Claim your repository ([How to claim a repo](claim_repo.html))
    - Use the Version Control + GitHub method to clone the repository to your computer.
2. Save [sample-data.csv](sample-data.csv) into your project directory. Mac users will need to Ctrl+click and select Download File.
3. Load the `tidyverse` package. This is the only package you will need.
4. Create a new R script and save it into the project directory. Put code for all the following steps in this R script.
5. Read the dataset and left assign it to an object in the R environment. 
    - Do not use the import dialog in RStudio.
    - Do write the appropriate R code and include it in your script.
6. For species A and B, what is the mean and standard error of height? To answer, print (in the console) a tibble exactly two rows (one for each species) and three 3 columns:
    - species,
    - mean height,
    - standard error of the mean height
7. Create a ggplot showing a histogram of heights with facets for Species (showing all three species)
8. Create a ggplot showing a scatterplot of heights and weights.  (using all three species)

Accomplishing step 6 above will require some data manipulation. This won't be spelled out on the practical, but steps in this analysis might include:

1. Exclude species `"C"` using `filter()`
2. For each species, calculating the mean, variance, and sample size (n) of each group using `group_by()` and `summarize`
3. For each species, calculate a new variable for standard error using `mutate()` and the formula `se = sqrt(var/n)`.
3. You need to remove missing values in either step 1 or 2 above.
4. Remove any extra columns you created except the three requested (species, mean, SE) using `select()` or `transmute()`
5. Print (in the console) a tibble with 3 colums


## Required packages

The only package you will be required to install and load is `tidyverse`.

## Functions to know

You will need to know a variety of functions including:

- basic R functions:
    - `library()`
- tidyverse functions for data import, tidying, and manipulating:
    - `read_csv()` — not read.csv()
    - `select()`
    - `filter()`  using the logical operators/functions `==`, `!=`, `<`, `>`, `<=`, `>=`, and the function `is.na()`
    - `mutate()`
    - `group_by()`
    - `summarize(x)` using these summary functions:
        - `mean(x)`
        - `var(x)`
        - `sd(x)`
        - `n()`
        - SE: `sd(x)/sqrt(n())`
- ggplot functions for plotting
    - `ggplot()` and `aes()`
    - `geom_histogram()`
    - `geom_point()`   [for scatterplots]
    - `facet_wrap()`
    - functions for adding labels to a ggplot
        - `labs()`, with the following arguments:
            - `title`
            - `x`
            - `y`
            - `color`, `size`, etc. depending on the aesthetics you mapped

- operators
    - `+ - / *` [mathematical operators]
    - `<-`      [left assign]
    - `%>%`     [pipe]
    - `+`       [used after calling `ggplot()`]

## Scoring

I will score the code and the plots in class when you are done.

The score will be out of 8 and will be graded holistically.

Rubric:

- A+ = 8   (earned for exceptionally thoughtful, creative, or efficient code)
- A = 7.5
- B = 6.5
- C = 5.5
- D = 4.5
- F = 3.5
