---
title: "Lab Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- [Overview](#overview)
- [Purpose](#purpose)
- [Datasets](#datasets)
- [Data Import Tips](#data-import-tips)
- [Assignment: Introduction & Methods](#assignment-introduction-methods)
- [Assignment: Results & Discusssion](#assignment-results-discusssion)
- [Assignment: Poster](#assignment-poster)

## Overview

A major part of the lab will be to perform your own exploratory data analysis in R.

You will choose a dataset to use and a question to answer. You will present your results to the class and at the [MSUM’s Andrew B. Conteh Student Academic Conference (SAC)](https://www.mnstate.edu/sac/) in April (application deadline is Feb. 25).

## Purpose

The purpose of the lab project is for you to practice working with real data, exploring data sets to answer a question that interests _you_, and communicating the results.

## Datasets

You may choose one of the following datasets, or choose another publicly available dataset, or use your own dataset, for example if you are involved in an ongoing research project.

### Your own dataset

If you are involved in an ongoing research project, for example with a faculty member at MSUM, you may be able to use the data collected as part of that project for your BIOL 275 lab project.

In order for you to choose your owsn dataset, it must be approved by the instructor first. In general, it needs to have enough data to be able to answer an interesting question.

### Ecology and Evolutionary Biology

- **[Plant growth in an aquaponic-based system](marry.html)**, a data set from MSUM Biosciences professor Dr. Mazz Marry.
- **[eBird data](https://ebird.org/science)** on bird observations. This is a huge dataset with many possible questions to explore. Possibilities include:
    - The relationship between abundance of a species and specific environmental conditions (e.g. climate, land cover)
    - The relationship between birding effort and number/diversity of birds observed
- The **Botanical Information and Ecology Network** brings together data on plant distribution, abundance, and traits, with the goal of predicting and mitigating the effects of climate change on plant species and communities. You can download geolocated observations and trait data, but you'd probably need to combine it with some other earth observation data like those found below.
- **[The Application for Extracting and Exploring Analysis Ready Samples (AρρEEARS)](https://lpdaacsvc.cr.usgs.gov/appeears/)** offers a simple and efficient way to access and transform geospatial data from a variety of federal data archives. 
    - AppEEARS enables users to subset geospatial datasets using spatial, temporal, and band/layer parameters.
    - Two types of sample requests are available: point samples for geographic coordinates and area samples for spatial areas via vector polygons.
    - There are [handy videos](https://www.youtube.com/watch?v=thRApFufBq8) on how to use the system to get data
    - Some datasets include:
        - Land Surface Temperature (min, max, mean)
        - Sea Surface Temperature
        - Precipitation
        - Snow cover
        - Land cover
        - Soil moisture, soil temperature
        - Vegetation indices (e.g. NDVI)
        - Gridded population data
    - The temporal and spatial range and resolution of these data sets varies.
    - You could explore geospatial data by itself, or if you have GPS coordinate for other types of data (e.g. georeferenced  specimen or observation data) then you could us AppEARS to extract environmental data associated with those points.
- Other geospatial data
    - **[National Land Cover Database](https://www.mrlc.gov/finddata.php)**. Could possible look at land cover change in a particular area.

### Cellular and molecular biology and biochemistry

- **[The Actinobacteriophage Database at PhagesDB.org](https://phagesdb.org/)**, a website that collects and shares data, pictures, protocols, and analysis tools associated with the discovery, sequencing, and characterization of [mycobacteriophages](https://phagesdb.org/glossary/#Mycobacteriophage)—viruses that infect the *Mycobacteria* and also other bacterial hosts in the phylum Actinobacteria. It was developed at—and is maintained from—the **Pittsburgh Bacteriophage Institute**, a joint venture of **Dr. Graham Hatfull** and **Dr. Roger Hendrix**, both of the Department of Biological Sciences at the University of Pittsburgh.
- **Neuroscience experiment from the Stocker Lab**. Dr. Stocker is exploring the effect of particular genes on brain development and behavior in mice. His dataset includes the results of a behavioral experiment.

### Health and medical

- **[Diabetes data](proj_diabetes.html)** from Dr. Bee Wisenden's lab.
- **[County Health Rankings & Roadmaps](http://www.countyhealthrankings.org/)**. A source of annual county-level public health data. You can download data by state and year (see [Minnesota](http://www.countyhealthrankings.org/app/minnesota/2017/downloads), for example).
- **[KIDS COUNT](http://datacenter.kidscount.org/)**. A source of data on children and families and a project of the Annie E. Casey Foundation. Data is available by year and county/state. You would need to choose and download the variables necessary to answer your question. Topics include:
    - Demographics
    - Economic Well-Being
    - Education
    - Family and Community
    - Health
    - Safety and Risky Behaviors
- Other sources of data sets:
    - **[Minnesota Health Data Sources](http://www.countyhealthrankings.org/using-the-rankings-data/finding-more-data/minnesota)**, a list compiled by County Health Rankings & Roadmaps.

### General online data repositories

- **[Dryad](http://datadryad.org/)**. A curated, general purpose data repository. You can search through it to find an interesting dataset. Here are two examples:
    - **[Mammal community data from Wen _et al._ (2018)](http://hdl.handle.net/10255/dryad.170813 )**. A dataset of mammal species found at sites along an elevational gradient on three mountains in China.
    - **[Birth seasonality data from Martinez-Bakker _et al._ (2014)](http://hdl.handle.net/10255/dryad.170822)**. A dataset of the number of births per month over the past 100 years in the US and 60 years in the World. Could possible be combined with another dataset to ask an interesting question.
- **[Awesome Public Datasets](https://github.com/awesomedata/awesome-public-datasets)**. A topic-centric list of high-quality open datasets in public domains. By everyone, for everyone! 

### Other useful datasets



### Datasets in R

Many R packages have datasets included.

## Data Import Tips

Where to store your data?

- ALWAYS in your project folder, never elsewhere on your computer
- Create a folder named `data`
- Add `data/` to your gitignore file
- download data files and save them into your `data/` folder
    - you can download manually (point and click in browser). if so, write the link to the data source in your README so its easy to find
    - you can download programatically with `download.file()` function

Importing your data

- never edit your raw data file. instead, read it as is and clean it up in R
- use read_csv() or readxl::read_excel()
    - do NOT use read.csv()
    - readxl package is installed with tidyverse, but not loaded
    - you have to load it yourself: library(readxl)
    - path argument: type "" put cursor in between and hit tab to autocomplete
 - read_excel() has a `sheet` argument to choose which sheet
- R puts back ticks around non-standard column names eg `
    - ` is a backtick, its on the upper left of the keyboard
    - standard names have only letters, numbers, `_` and `.`
    - any name with special characters or starts with a number is considered non-standard. 
    - its a good idea to rename these columns
- You can rename columns during import with the col_names argument to `read_*()` or using `dplyr::rename()`
- You can skip rows using the skip argument to `read_*()`
- When you play with `skip` argument, sometimes you need to change the `col_names` argument too
- You can read only a set number of rows using the `n_max` argument

## Assignment: Introduction & Methods

**DUE: April 3-4 (come to lab with this assignment done.)**

1. Create a new R Markdown file to hold your poster content
2. 

## Assignment: Results & Discusssion

**DUE: April 10-11 (come to lab with this assignment done.)**


## Assignment: Poster

After you finish preparing the content for your poster, you will copy and paste it on to your poster and format the poster for printing.

Stay tuned for more information, including a template poster.