## Quarto

## Lab report in Quarto

In this course, you will learn to write your reports using [Quarto](https://quarto.org/), a system developed by Posit to allow you to weave narrative text and R code and output into elegant documents including HTML, PDF, Word, PowerPoint, and more. The process is code-based, so it is fully reproducible.

In your new RStudio project, inspect the list of files shown in the Files tab in the bottom right pane.

1.  Create a new file... a Quarto Document... and name it `report.qmd`
2.  Look at the document and you will see the following:
3.  **Metadata** at the top, beginning and ending with three dashes `---`. This is called the YAML header and contains information about how the document should be rendered when you make your lab report from it. Put your name in the author field, but otherwise leave it as is.
4.  Some **narrative text** including headings, paragraphs, and numbered lists.
5.  Some vertical lines with the word "answer" after them. These are where you will write your answers to the questions. The formatting used here is called a "blockquote". This will be handy to know when you need to add and format your own answers.
6.  R code chunks. These look like colored boxes that begin with `{r}`. This is where you can put R code. Think of each box as its own little R script. Or more accurately, that all the chunks in a given Quarto document together form a script. For example, if you run the code `x <- 1` in one chunk and then run `print(x)` in the next code chunk, it will remember `x` and print it correctly in the second chunk. In other words, the environment is maintained from chunk to chunk.

Why include R code chunks in the document? There are two main reasons:

1.  To show the output of the code. This could be graphical output, like a bar chart or scatterplot, or text output like the results from a statistical hypothesis test.
2.  To show the instructor you know what code to run to answer a question.

In this way, you can weave together narrative text and the output of R code. No more copying images from R and pasting them into a Word document to create a report. In fact, you can actually [export your document as a Word document](https://quarto.org/docs/output-formats/ms-word.html) by changing one line of the YAML header. Other formats Quarto can create include PDF and PowerPoint.

## Render your report

Your `report.qmd` document already contains some text to get you started.

One thing you will need to know is how to convert your Quarto file into your lab report, a process RStudio calls "rendering".

To render your lab report, click the "Render" button and wait while the process completes. A new tab should open in your web browser showing the rendered lab report.

Compare how the rendered lab report compares to the original Quarto document and you will see a few changes:

-   The title, subtitle, author, and date from the YAML header are now formatted nicely

-   There is a table of contents on the right side

-   The first R code chunk, which contains the `library()` commands, has been run. You can now see both the code you supplied in the R code chunk and the output of that code. In this case, the output is the message about which tidyverse packages were loaded and which function names have conflicts. Its the same output you would see in your console if you ran that code yourself in R.

-   The last code chunk has been rendered, showing your session info, which includes your operating system, version of R, and which packages were loaded when you created the lab report.

You will also notice that there is a new `report.html` file in your project directory, as well as a folder named `report_files`. The folder contains a variety of files needed to show the HTML file correctly. In the future, it will contain any images generated by R, for example plots created by ggplot.
