# R Markdown documents

R Markdown documents (.Rmd) are a special kind of Markdown document that lets you insert chunks of code. When knitted, they are turned into another file with the code chunk replaced by nicely formatted code *and its output*.

The output code be what appears in your console if you were to run the code, or it could be a table or figure. Code chunks can contain many types of code, including R code.

R Markdown documents can be knitted to a variety of file types including Markdown, (.md), web page (.html), PDF (.pdf), Microsoft Word (.docx), and many more.

## Components of an R Markdown document

There are three main components to an R Markdown document:

-   A YAML header
-   Narrative text
-   Chunks of R code that R will run when you "knit" the document

Let's look at each component in more depth.

### YAML header

You will notice some header information at the top, between two sets of three dashes, that looks like this:

``` {.yaml}
---
title: "Lab 2 Assignment"
author: "___"
date: "`r format(Sys.Date())`"
output: github_document
---
```

When you knit the document, R will use the title as the page title and will put the author and date on the next line.

Notice that instead of writing the date in text, there is some R code. This is called *inline* R code in an R Markdown document. When you want to insert something generated by R into your text, you can use this kind of code. Inline code should start with a backtick and the letter r `` `r `` and end with another backtick `` ` ``. Here is another example of inline code:

> One plus one is `` `r 1 + 1` ``

When R knits that it will appear as

> One plus one is 2

### Narrative text

This includes thinks like paragraphs of text, headings, lists, quoted text, etc. Think of this as the body of the report.

This is written in the Markdown language, a simple way to tell places like R and GitHub how it should look on the screen.

You can learn more about how to format your text in Markdown using these resources:

-   In the Go to the **Help** menu in RStudio and select **Markdown Quick Reference**
-   [Basic Syntax](https://www.markdownguide.org/basic-syntax/ "Basic Syntax | Markdown Guide") on the Markdown Guide website

The new version of RStudio (version 1.4) has a very handy WYSIWYG (what you see is what you get) editor for R Markdown which allows you to write R Markdown documents like a word processor like Microsoft Word. To make use of this, download and install the newest version of RStudio.

### Code Chunks

Code chunks are bits of R code that are executed when you knit the document. In the resulting Markdown (or other type) of document, the code is replaced by its output, which usually consist of text, tables or figures.

#### Parts of a code chunk

A code chunk looks like the following:

> ```` {.markdown}
> ```{r chunk-name, arg1=val1, arg2=val2}
>
> ```
> ````

**Blank line.** Always put a blank line before a code chunk to separate it from the preceding text.

**Opening backticks.** The three backticks ```` ``` ```` tell R to expect a chunk of code.

**Curly braces.** The curly braces tell R what kind of code to expect, the name of the code chunk, and some options for how to knit it. For example, in the code above, the `r` tells R to expect R code, and `chunk-name` is the name of the code chunk.

**Chunk names.** Names are not required, but they can be useful. When you try to knit your R Markdown document, any errors will show in the Markdown tab (bottom left pane). Having your code chunks named makes it easier to figure out where the error occurred. If you don't want to give your chunk a name, just end the curly brackts like this: `{r}`

**Chunk arguments.** Optionally, if you want to modify the way the chunk gets turned into code or figures, you can do so with a variety of arguments. For example, the argument `echo=FALSE` will prevent the code from being shown in the output. You can also set argument in RStudio by clicking the gear icon on the right side of a code chunk.

**Code.** The blank line between the closing curly brace and the next three backticks is where the code goes.

**Closing backticks.** The three backticks ```` ``` ```` tell R to end the code chunk.

#### Example code chunk

Here's an example of a code chunk with actual R code:

> ```` {.markdown}
> ```{r print-x}
> x <- 1    # x gets a value of 1
> x         # print the value of x
> ```
> ````

Anything you can write in an R script, you can write in an R code chunk, including comments, as seen above.

#### Running a code chunk

You can run a code chunk and preview the output by clicking the green Play button one the right side of the first line of the chunk.

If the chunk code depends on code in previous chunks being run first, there is another button next to the play button that runs all previous code chunks.

It is possible to highlight lines of code and run them individually. Troubleshooting code in R chunks, however, is much easier in an R script, so it usually best to develop a working R script first, then copy bits of code from it and paste them into code chunks in your R Markdown document.

## Knitting

When you are ready to have RStudio create the final product from your R Markdown document, click the Knit button on the source tab toolbar (it looks like a ball of blue yarn with a needle).

RStudio will switch to the R Markdown tab in the bottom left pane. If it finds no errors in the document, a preview window will pop up showing you approximately what the final product will look like. Check it over to make sure it looks fine. Note that links to other documents will likely not work at this stage.
